Unboxed types version 3 tests
ocaml-flambda/ocaml-jst pull request #82
Opened 2022-12-15 14:16 UTC by goldfirere

This covers the addition of `or_null`, which comprises v3 of the unboxed-types plan. This test is skipped (and so can be merged now), but someone should review this, as it is intended to include the entire specification for the `or_null` feature.

2022-12-15 15:57 UTC, lpw25 commented
Here's one we could consider:
```ocaml
let foo x = (x : int list :> int or_null list)
```

2022-12-15 20:58 UTC, goldfirere commented
> Here's one we could consider:
> 
> ```ocaml
> let foo x = (x : int list :> int or_null list)
> ```

Great idea. I've added this.

2023-03-17 14:48 UTC, ccasin requested changes
Looks good - a few minor comments, and I think several spots need to be updated for the current thinking on layout annotations.

2023-03-17 14:48 UTC, ccasin commented on testsuite/tests/typing-layouts/or_null.ml
> +type q = (int t : immediate)  (* but t isn't abstract, so this is OK *)
annotation syntax

2023-03-17 14:48 UTC, ccasin commented on testsuite/tests/typing-layouts/or_null.ml
> +|}]
Maybe a note here that the error message had better be very good (perhaps with an explicit hint) because needing a `value` annotation is unusual.

2023-03-17 14:48 UTC, ccasin commented on testsuite/tests/typing-layouts/or_null.ml
> +|}]
Probably note that `q` should be immediate, or add an annotation.

2023-03-21 09:51 UTC, goldfirere commented on testsuite/tests/typing-layouts/or_null.ml
> +  (* unlike [option] we cannot have [join] *)
I lean against, for now at least.

2023-03-22 12:46 UTC, ccasin commented
Thanks.  Merging despite the failing i386 test because that can't possibly be related.

2023-03-22 12:47 UTC, merged